CREATE TABLE IF NOT EXISTS users (
 id TEXT PRIMARY KEY, name TEXT NOT NULL, surname TEXT NOT NULL,
 identity_key TEXT NOT NULL UNIQUE, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS user_sessions (
 token_hash TEXT PRIMARY KEY, user_id TEXT NOT NULL REFERENCES users(id), expires_at REAL NOT NULL);
CREATE TABLE IF NOT EXISTS activity_log (
 id TEXT PRIMARY KEY, user_id TEXT REFERENCES users(id), actor TEXT NOT NULL,
 action TEXT NOT NULL, target TEXT NOT NULL, status INTEGER NOT NULL,
 created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
ALTER TABLE datasets ADD COLUMN deleted_at TEXT;
ALTER TABLE runs ADD COLUMN deleted_at TEXT;
ALTER TABLE jobs ADD COLUMN initiated_by TEXT REFERENCES users(id);
