const $ = (selector, root = document) => root.querySelector(selector);
const $$ = (selector, root = document) => [...root.querySelectorAll(selector)];
const escape = value => String(value ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const json = value => escape(JSON.stringify(value, null, 2));
const S = {caseJobs:new Set(),selectedCases:new Set(),selectedReferences:new Set(),users:[],referenceJobs:new Set(),user:null,view:'overview', app:'', bootstrap:{applications:[],metrics:[],categories:[]}, catalog:{questions:[],technologies:[]}, datasets:[], cases:[], chunks:[], runs:[], results:[], rag:null, run:'', dataset:'', selectedQuestions:new Set(), epoch:0};
const icons = {overview:'<rect x="3" y="3" width="7" height="7" rx="1"/><rect x="14" y="3" width="7" height="7" rx="1"/><rect x="3" y="14" width="7" height="7" rx="1"/><rect x="14" y="14" width="7" height="7" rx="1"/>',applications:'<rect x="3" y="5" width="18" height="15" rx="2"/><path d="M3 10h18M7 7.5h.1M10 7.5h.1"/>',rag:'<path d="M6 3h9l4 4v14H6zM14 3v5h5M9 12h7M9 16h7"/>',datasets:'<ellipse cx="12" cy="5" rx="8" ry="3"/><path d="M4 5v7c0 4 16 4 16 0V5M4 12v7c0 4 16 4 16 0v-7"/>',references:'<path d="M4 4h6c2 0 2 2 2 2s0-2 2-2h6v16h-6c-2 0-2 1-2 1s0-1-2-1H4zM12 6v15"/>',runs:'<path d="m8 5 12 7-12 7z"/>',results:'<path d="M4 3v18h17M8 16v-5M13 16V7M18 16v-8"/>',settings:'<path d="M5 6h14M5 12h14M5 18h14"/><circle cx="9" cy="6" r="2"/><circle cx="15" cy="12" r="2"/><circle cx="9" cy="18" r="2"/>'};
icons.users=icons.settings;
const nav = [['overview','Overview'],['applications','Applications'],['rag','RAG testing'],['datasets','Datasets'],['references','Reference library'],['runs','Test runs'],['results','Results'],['users','Users']];
$('#navigation').innerHTML = nav.map(([id,label])=>`<a href="#${id}" data-view="${id}"><svg viewBox="0 0 24 24" aria-hidden="true">${icons[id]}</svg>${label}</a>`).join('');

async function api(path, body, method) {
  const options = {method:method || (body ? 'POST':'GET'), headers:{}};
  if(body instanceof FormData) options.body=body;
  else if(body !== undefined){options.headers['Content-Type']='application/json';options.body=JSON.stringify(body);}
  const response = await fetch('/api'+path, options);
  let data;
  try {data=await response.json();} catch {throw new Error('The server returned an unreadable response.');}
  if(response.status===404 && (path==='/session'||path.includes('interview-')||path.includes('cloud-status'))) throw new Error('Restart your local E.V.O server with Start-EVO.ps1, then refresh this page to load the new automation.');
  if(response.status===401)showSignIn();
  if(!response.ok) throw new Error(typeof data.detail==='string'?data.detail:'Check the required input fields.');
  return data;
}
let toastTimer;
function toast(message,error=false){clearTimeout(toastTimer);const node=$('#toast');node.textContent=message;node.className='toast show'+(error?' error':'');toastTimer=setTimeout(()=>node.classList.remove('show'),7000);}
const button=(label,action,extra='',primary=false)=>`<button class="button${primary?' primary':''}" data-action="${action}" ${extra}>${label}</button>`;
const badge=(text)=>{const green=['passed','completed','approved','connected'];const red=['failed','execution_error','evaluation_error','needs_review'];const amber=['pending','paused','unverified','partial','interrupted','generated'];return `<span class="badge ${green.includes(text)?'green':red.includes(text)?'red':amber.includes(text)?'amber':'blue'}">${escape(text?.replaceAll('_',' ')||'not evaluated')}</span>`;};
const when=value=>value?new Date(value.replace(' ','T')+(value.includes('Z')?'':'Z')).toLocaleString([], {month:'short',day:'numeric',hour:'2-digit',minute:'2-digit'}):'—';
const field=(name,label,value='',type='text',help='')=>`<div class="field"><label for="${name}">${label}</label><input id="${name}" name="${name}" type="${type}" value="${escape(value)}" ${type==='password'?'autocomplete="new-password"':''}>${help?`<small>${help}</small>`:''}</div>`;
const select=(name,label,options,value,help='')=>`<div class="field"><label for="${name}">${label}</label><select id="${name}" name="${name}">${options.map(o=>{const [v,l]=Array.isArray(o)?o:[o,o];return `<option value="${escape(v)}" ${v===value?'selected':''}>${escape(l)}</option>`;}).join('')}</select>${help?`<small>${help}</small>`:''}</div>`;
const heading=(title,description,actions='')=>`<div class="page-heading"><div><div class="eyebrow">AI quality workspace</div><h1>${title}</h1><p>${description}</p></div><div class="actions">${actions}</div></div>`;
const panel=(title,description,body,actions='')=>`<section class="panel"><div class="panel-head"><div><h2>${title}</h2>${description?`<p>${description}</p>`:''}</div>${actions}</div>${body}</section>`;
const empty=(title,description,action='')=>`<div class="empty"><div class="empty-icon">◇</div><h3>${title}</h3><p>${description}</p>${action}</div>`;
const appOptions=()=>S.bootstrap.applications.map(a=>`<option value="${a.id}" ${S.app===a.id?'selected':''}>${escape(a.name)}</option>`).join('');
const appPicker=()=>`<select class="control" id="app-picker" aria-label="Application">${appOptions()}</select>`;
const currentApp=()=>S.bootstrap.applications.find(a=>a.id===S.app);
const table=(headers,rows)=>`<div class="table-wrap"><table><thead><tr>${headers.map(h=>`<th>${h}</th>`).join('')}</tr></thead><tbody>${rows.join('')}</tbody></table></div>`;
function modal(title,body){$('#modal-content').innerHTML=`<header class="modal-head"><h2>${title}</h2><button class="modal-close" data-action="close" aria-label="Close dialog">×</button></header><div class="modal-body">${body}</div>`;if(!$('#modal').open)$('#modal').showModal();}
const closeModal=()=>$('#modal').close();
function download(name,data,type='application/json'){const link=document.createElement('a');link.href=URL.createObjectURL(new Blob([typeof data==='string'?data:JSON.stringify(data,null,2)],{type}));link.download=name;link.click();setTimeout(()=>URL.revokeObjectURL(link.href),1000);}
function formData(form){return Object.fromEntries(new FormData(form));}
function checked(form,name){return $$(`input[name="${name}"]:checked`,form).map(n=>n.value);}
function showSignIn(){S.user=null;S.results=[];S.datasets=[];S.cases=[];S.app='';S.run='';S.dataset='';$('#content').innerHTML='';$('#user-display').textContent='';$('#modal').close();document.body.classList.add('signed-out');}
async function bootstrap(){S.bootstrap=await api('/bootstrap');if(!S.bootstrap.applications.some(a=>a.id===S.app))S.app=S.bootstrap.applications[0]?.id||'';}
async function render(){
  const session=await api('/session');if(!session.user){showSignIn();return;}S.user=session.user;document.body.classList.remove('signed-out');$('#user-display').textContent=Array.from(S.user.name)[0].toUpperCase()+'. '+S.user.surname;
  const epoch=++S.epoch;S.view=location.hash.slice(1)||'overview';
  if(![...nav.map(n=>n[0]),'settings'].includes(S.view))S.view='overview';
  $$('#navigation a').forEach(a=>a.classList.toggle('active',a.dataset.view===S.view));
  $('#breadcrumb').textContent=nav.find(n=>n[0]===S.view)?.[1]||'Settings';
  $('#content').innerHTML='<div class="loading"><span class="spinner"></span>Loading workspace…</div>';
  try{await bootstrap();const html=await views[S.view]();if(epoch===S.epoch){$('#content').innerHTML=html;$('#connection-status').innerHTML='<span class="dot"></span>Local workspace';}}
  catch(e){if(epoch===S.epoch)$('#content').innerHTML=empty('Unable to load this page',escape(e.message),button('Try again','refresh'));}
}

const views={
  async users(){S.users=await api('/users');const userTable=rows=>table(['Name','Surname','Created',''],rows.map(u=>`<tr><td>${escape(u.name)}</td><td>${escape(u.surname)}</td><td>${when(u.created_at)}</td><td>${u.deleted_at?button('Restore','restore-user',`data-id="${u.id}"`):button('Edit','edit-user',`data-id="${u.id}"`)+button('Remove','delete-user',`data-id="${u.id}"`)}</td></tr>`));return heading('Users','Add and edit the names used for local sign-in and activity tracking.',button('Add user','add-user','',true))+panel('Workspace users','Existing names are reused at sign-in.',userTable(S.users.filter(u=>!u.deleted_at)))+`<details class="section-gap"><summary>Removed users (${S.users.filter(u=>u.deleted_at).length})</summary>${userTable(S.users.filter(u=>u.deleted_at))}</details><div class="notice">Name-only sign-in is self-declared. Users share this workspace and can manage its users. Editing a name preserves the user ID and earlier audit entries. Removed users cannot sign in until restored.</div>`;},
  async overview(){
    const d=await api('/dashboard');
    const stats=[['Connected applications',S.bootstrap.applications.length,'Ready for configuration','▧'],['Discovered questions',d.questions,`${d.technologies} technologies in your catalog`,'⌘'],['Questions tested',d.tested_questions,`${d.pending} test cases pending`,'✓'],['Average quality score',d.average_quality===null?'—':d.average_quality.toFixed(2),'Evaluation quality · 0 to 1','↗']];
    const recent=d.runs.length?table(['Application / run','Started','Status',''],d.runs.slice(0,5).map(r=>`<tr><td class="strong">${escape(r.application)}<small class="mono">${r.id.slice(0,8)}</small></td><td>${when(r.created_at)}</td><td>${badge(r.status)}</td><td>${button('View results','open-run',`data-id="${r.id}"`)}</td></tr>`)):empty('Your first evaluation starts here','Connect an application, add test cases, and run an evaluation to see results in this workspace.',button('Create a test run','new-run','',true));
    const chart=d.technologies_breakdown.length?`<div class="bars">${d.technologies_breakdown.map(t=>`<div><div class="bar-label"><span>${escape(t.name)} <span class="subtle">/ ${escape(t.application)}</span></span><strong>${t.questions}</strong></div><div class="bar"><span style="width:${Math.max(2,t.questions/Math.max(...d.technologies_breakdown.map(x=>x.questions),1)*100)}%"></span></div></div>`).join('')}</div>`:`<div class="chart-empty"><div class="empty-icon">⌁</div><h3>No catalog data yet</h3><p>Import questions to see coverage by technology.</p></div>`;
    return heading('Workspace overview','A clear view of your AI quality, coverage, and testing activity.',button('<span class="plus">+</span> New test run','new-run','',true))+`<div class="stats">${stats.map(([l,v,h,s])=>`<div class="stat-card"><div class="stat-label">${l}<span class="stat-symbol">${s}</span></div><div class="stat-value">${v}</div><div class="stat-detail">${h}</div></div>`).join('')}</div><div class="grid-2">${panel('Question coverage','Discovered questions across your technologies',chart,`<span class="badge">${d.technologies} technologies</span>`)}${panel('Evaluation health','Keep quality failures separate from execution issues',`<div class="panel-body"><div class="health-row"><div>Evaluation failures<small>Responses below selected quality thresholds</small></div><span class="health-value">${d.failed}</span></div><div class="health-row"><div>Execution issues<small>Connection, capture, or judge errors</small></div><span class="health-value">${d.errors}</span></div><div class="health-row"><div>Candidate score accuracy<small>Against approved score ranges</small></div><span class="health-value">${d.candidate_score_accuracy===null?'—':Math.round(d.candidate_score_accuracy*100)+'%'}</span></div></div>`)}</div>${panel('Recent test runs','Track progress and review your latest evaluations',recent,`<a class="row-link" href="#runs">View all runs →</a>`)}<div class="section-heading"><h2>Your testing workflow</h2><span class="subtle">From connection to confidence</span></div><div class="workflow"><div class="workflow-card"><div class="step">01 / CONNECT</div><h3>Bring your AI application</h3><p>Use a website, an authorized API, or exported input/output records.</p><a href="#applications">Manage applications →</a></div><div class="workflow-card"><div class="step">02 / PREPARE</div><h3>Build reliable test data</h3><p>Review reference concepts, generate candidate answers, and approve expectations.</p><a href="#datasets">Explore datasets →</a></div><div class="workflow-card"><div class="step">03 / EVALUATE</div><h3>Measure what matters</h3><p>Run appropriate DeepEval metrics and inspect every score, reason, and result.</p><a href="#results">View evaluation results →</a></div></div>`;
  },
  async applications(){
    if(S.app)S.catalog=await api('/catalog/'+S.app);
    const apps=S.bootstrap.applications;
    const cards=apps.length?`<div class="application-cards">${apps.map(a=>`<div class="application-card"><div class="actions" style="justify-content:space-between"><div class="app-icon">${a.kind==='import'?'↧':a.kind==='api'?'⌘':'▧'}</div>${badge(a.kind)}</div><h3>${escape(a.name)}</h3><div class="app-url">${escape(a.config.url||'Exported records · no live connection required')}</div><div class="actions">${button('Configure','edit-connection',`data-id="${a.id}"`)}${button('Remove','delete-application',`data-id="${a.id}"`)}${a.config.url?.startsWith('https://50.62.181.23:8501')?button('Interview automation','interview-setup',`data-id="${a.id}"`,true):''}${a.config.adapter==='interview_api'?button('First automated test','interview-first-test',`data-id="${a.id}"`):''}${a.kind==='browser'||a.kind==='interview'?button('Sign in','login',`data-id="${a.id}"`):''}${button('Check connection','diagnostics',`data-id="${a.id}"`)}</div></div>`).join('')}</div>`:empty('Connect your first application','Create a connection to an AI interview tool, chatbot, API, or offline evaluation records.',button('Add application','new-connection','',true));
    const catalog=S.app?`<div class="section-heading"><h2>Technology & question catalog</h2><span class="subtle">Reuse collected questions across test runs</span></div>${panel('Question catalog','Verified coverage requires an authoritative complete catalog.',`<div class="toolbar">${appPicker()}<select id="technology-filter" class="control" aria-label="Filter technology"><option value="">All technologies</option>${S.catalog.technologies.map(t=>`<option>${escape(t.name)}</option>`).join('')}</select><span class="spacer"></span>${button('Import catalog','import-catalog')}${button('Discover technologies','sync-technologies',discoveryReady(true)?'':'disabled title="Check connection or import a catalog first"')}${button('Sync questions','sync-questions',discoveryReady(false)?'':'disabled title="Check connection or import a catalog first"',true)}</div><div id="question-table">${questionTable()}</div>${coverage()}`)}`:'';
    return heading('Applications','Connect your systems and build a reusable question catalog.',button('<span class="plus">+</span> Add application','new-connection','',true))+cards+catalog+jobRegion();
  },
  async references(){
    S.chunks=await api('/chunks?kind=structured'+(S.app?'&app_id='+S.app:''));
    return heading('Reference library','Review the concepts and rubrics your evaluations depend on.',button('Export references','export-references'))+panel('Structured evaluation chunks','Every version retains its source and review status.',`<div class="toolbar">${appPicker()}<select id="chunk-kind" class="control" aria-label="Chunk type"><option value="structured">Structured question chunks</option><option value="document">Document chunks</option></select><span class="spacer"></span><span class="subtle">${currentChunks().length} questions</span></div><div class="toolbar" id="reference-bulk-toolbar">${button('Select all unapproved','select-all-references')}${button('Clear selection','clear-references')}${button('Generate proposals for selected','bulk-generate-references')}${button('Approve & save selected','bulk-approve-references','',true)}<span id="reference-selection-count" class="subtle"></span><label class="check"><input type="checkbox" id="reference-history">Show history</label><label class="check"><input type="checkbox" id="reference-approved-only">Approved only</label></div><div id="chunks-table">${chunkTable()}</div>`)+`<div class="notice">Generated reference information is an independent proposal until reviewed. Saving a new version preserves previous versions and existing test-run snapshots.</div>`+jobRegion();
  },
  async datasets(){
    if(!S.app)return heading('Datasets','Reusable test cases for your AI applications.')+empty('Add an application first','An offline connection is enough to import and evaluate exported records.',button('Add application','new-connection','',true));
    [S.datasets,S.catalog]=await Promise.all([api('/datasets/'+S.app),api('/catalog/'+S.app)]);
    if(!S.datasets.some(d=>d.id===S.dataset))S.dataset=S.datasets[0]?.id||'';
    if(S.dataset)S.cases=await api('/dataset/'+S.dataset+'/cases');else S.cases=[];
    return heading('Datasets','Create, review, and reuse candidate answers and expected outcomes.',button('Import dataset','import-dataset')+button('<span class="plus">+</span> Generate test cases','generate-dataset','',true))+panel('Saved datasets','Generated and imported expectations remain unverified until you approve them.',`<div class="toolbar">${appPicker()}<span class="spacer"></span><span class="subtle">${S.datasets.length} datasets</span></div>${S.datasets.length?table(['Dataset','Cases','Source','Version',''],S.datasets.map(d=>`<tr><td class="strong">${escape(d.name)}<small>${when(d.created_at)}</small></td><td>${d.cases}</td><td>${escape(d.source)}</td><td>v${d.version}</td><td>${button('Review cases','select-dataset',`data-id="${d.id}"`)}${button('Delete','delete-dataset',`data-id="${d.id}"`)}</td></tr>`)):empty('Build your first dataset','Import candidate answers or generate them from approved question references.')}`)+(S.dataset?panel('Test case review',S.datasets.find(d=>d.id===S.dataset)?.name||'',`<div class="toolbar">${button('Select all unapproved','select-all-cases')}${button('Clear selection','clear-cases')}${button('Generate proposals for selected','generate-case-proposals')}${button('Approve & save selected','approve-cases','',true)}</div>`+table(['Select','Question','Technology','Category','Review status',''],S.cases.map(c=>`<tr><td>${c.validation!=='approved'?`<input type="checkbox" data-case-id="${c.id}" aria-label="Select test case" ${S.selectedCases.has(c.id)?'checked':''}>`:''}</td><td class="strong truncate">${escape(c.question)}</td><td>${escape(c.technology)}</td><td>${escape(c.content.category||'Imported')}</td><td>${badge(c.validation)}</td><td>${button('Review','review-case',`data-id="${c.id}"`)}</td></tr>`)),button('Export dataset','export-dataset')):'')+jobRegion();
  },
  async runs(){
    S.runs=await api('/runs');
    return heading('Test runs','Execute controlled batches with persistent progress and safe recovery.',button('<span class="plus">+</span> New test run','new-run','',true))+`<div id="run-list">${runCards()}</div>`+`<div class="notice">Runs execute sequentially per application. Pause and cancel take effect between cases. An ambiguous submission is held for review and is never automatically repeated.</div>`+jobRegion();
  },
  async results(){
    S.runs=await api('/runs');if(!S.runs.some(r=>r.id===S.run))S.run=S.runs[0]?.id||'';
    S.results=S.run?await api('/runs/'+S.run+'/results'):[];
    return heading('Evaluation results','Inspect input, reference, application feedback, and evaluation quality.',S.run?`<a class="button" href="/api/runs/${S.run}/export?format=csv">Export CSV</a><a class="button" href="/api/runs/${S.run}/export?format=json">Export JSON</a><a class="button" href="/api/runs/${S.run}/export?format=pdf">PDF</a><a class="button" href="/api/runs/${S.run}/export?format=docx">Word</a>`:'')+panel('Run results','Candidate scores and evaluation-quality scores are shown separately.',`<div class="toolbar"><select id="result-run" class="control" aria-label="Select run">${S.runs.map(r=>`<option value="${r.id}" ${r.id===S.run?'selected':''}>${escape(r.application)} · ${when(r.created_at)} · ${r.id.slice(0,8)}</option>`).join('')}</select><select id="result-status" class="control" aria-label="Result status"><option value="">All statuses</option>${[...new Set(S.results.map(r=>r.state))].map(s=>`<option value="${s}">${escape(s)}</option>`).join('')}</select><select id="result-technology" class="control" aria-label="Result technology"><option value="">All technologies</option>${[...new Set(S.results.map(r=>r.snapshot.technology))].map(t=>`<option>${escape(t)}</option>`).join('')}</select></div><div id="results-table">${resultsTable()}</div>`);
  },
  async settings(){
    const c=await api('/settings');
    return heading('Workspace settings','Configure the providers and services used by this local workspace.',button('User activity','activity'))+panel('Provider configuration','Secrets are kept in server memory for this session, never in source code.',`<div class="panel-body"><form id="settings-form"><div class="form-section"><h3>Evaluation model</h3><div class="form-grid">${field('openai_key','OpenAI API key','','password',c.openai_configured?'A key is already configured. Leave blank to retain it.':'Required for synthesis and LLM-judged metrics.')}${field('judge_model','Judge model',c.judge_model,'text','Deterministic checks do not make paid model calls.')}</div></div><div class="form-section"><h3>Confident AI</h3>${field('confident_key','Confident AI API key','','password',c.confident_configured?'Configured. Leave blank to retain.':'Automatically uploads test cases and measured results after a run.')}<p>Local results remain available if cloud sync fails. Add this key and retry cloud sync later without resubmitting answers.</p></div><div class="form-section"><h3>Existing RAG integration</h3><div class="form-grid">${field('webhook_url','RAG endpoint URL',c.webhook_url,'url','The existing n8n/webhook integration remains available.')}${field('supabase_url','Supabase project URL',c.supabase_url,'url')}${field('supabase_key','Supabase key','','password',c.supabase_configured?'Supabase is configured. Leave blank to retain the key.':'Optional: local SQL storage works without Supabase.')}${field('supabase_table','Supabase table',c.supabase_table)}</div></div><div class="notice">Use environment variables for credentials you want to retain after restarting the server. Browser authentication uses a local storage-state file or environment-variable references in the connection configuration.</div><div class="form-actions"><button class="button primary" type="submit">Save settings</button></div></form></div>`);
  },
  async rag(){
    S.rag=await api('/rag');
    return heading('RAG testing','Your document-to-evaluation workflow, now in the web workspace.',button('View provider settings','settings'))+`<div class="grid-2">${panel('Upload & process','PDF, DOCX, TXT, CSV, and XLSX · maximum 20 MB',`<div class="panel-body"><form id="upload-form"><div class="file-drop"><div class="empty-icon">↥</div><strong>Choose a source document</strong><p>Document text is extracted, chunked, and stored in SQL.</p><input name="file" type="file" required accept=".pdf,.docx,.txt,.csv,.xlsx" aria-label="Source document"></div><div class="form-grid section-gap">${field('chunk_size','Chunk size (words)',1000,'number')}${field('overlap','Overlap (words)',200,'number')}</div><label class="check section-gap"><input type="checkbox" name="sync_supabase" value="true"><span>Also upload chunks to Supabase<small>Uses your existing project and table configuration.</small></span></label><div class="form-actions"><button class="button primary" type="submit">Upload & process</button></div></form></div>`)}${panel('Documents','Reuse stored document chunks for golden generation',S.rag.documents.length?table(['Document','Chunks',''],S.rag.documents.map(d=>`<tr><td class="strong">${escape(d.name)}</td><td>${d.chunks}</td><td>${button('Generate goldens','rag-synthesize',`data-id="${d.document_id}"`)}</td></tr>`)):empty('No documents yet','Upload a document to begin your RAG testing workflow.'))}</div>${panel('Golden datasets & evaluations','Review expected answers before evaluating your RAG endpoint.',S.rag.snapshots.length?table(['Dataset','Cases','Created',''],S.rag.snapshots.map(s=>`<tr><td class="strong">${escape(s.label)}</td><td>${s.goldens.length}</td><td>${when(s.created_at)}</td><td><div class="actions">${button('Review','rag-review',`data-id="${s.id}"`)}${button('Evaluate','rag-evaluate',`data-id="${s.id}"`)}</div></td></tr>`)):empty('No golden datasets yet','Generate Q&A from stored document chunks, or restore existing RAG checkpoints.'))}`+jobRegion();
  }
};

function discoveryReady(technologies){const a=currentApp(),c=a?.config||{};return a?.kind==='api'?!!(c.catalog_path||c.adapter==='interview_api'):a?.kind==='import'?false:technologies?!!(c.technology_select||c.technology_options||c.catalog_rows):!!(c.catalog_rows||c.question);}
function questionTable(){const technology=$('#technology-filter')?.value||'';const rows=S.catalog.questions.filter(q=>!technology||q.technology===technology);return rows.length?table(['Question','Technology','Difficulty','Observed',''],rows.map(q=>`<tr><td class="strong truncate" title="${escape(q.text)}">${escape(q.text)}<small class="mono">${q.id}</small></td><td>${escape(q.technology)}</td><td>${escape(q.difficulty||'—')}</td><td>${q.observations}</td><td>${button('Reference','question-reference',`data-id="${q.id}"`)}</td></tr>`)):empty('No questions in this catalog','Import an authorized catalog, or configure discovery for an accessible application.');}
function coverage(){const d=S.catalog.discoveries?.[0];if(!d)return '<div class="panel-body subtle">Coverage has not been verified. Technology lists and observed questions can still be stored and reused.</div>';return `<div class="panel-body"><div class="tiny-label">Latest synchronization · ${when(d.created_at)}</div><div class="actions">${Object.entries(d.statistics.technologies).map(([name,v])=>`<span class="badge ${v.complete?'green':'amber'}">${escape(name)} · ${v.unique_questions} questions · ${v.complete?'complete catalog verified':'observed coverage'}</span>`).join('')}</div><p>${d.statistics.duplicates} duplicate observations · ${d.statistics.new_questions} newly collected questions</p></div>`;}
function currentChunks(){const latest=new Map();for(const c of S.chunks){if(c.kind!=='structured'||!c.active)continue;if(!latest.has(c.question_id)||latest.get(c.question_id).version<c.version)latest.set(c.question_id,c);}return [...latest.values()];}
function selectedChunks(){return currentChunks().filter(c=>c.validation!=='approved'&&S.selectedReferences.has(c.question_id));}
function chunkTable(){const latest=new Set(currentChunks().map(c=>c.id)),rows=$('#reference-history')?.checked?S.chunks:S.chunks.filter(c=>c.kind!=='structured'||latest.has(c.id));return rows.length?table(['Select','Source / question','Version','Review status','Active',''],rows.filter(c=>!$('#reference-approved-only')?.checked||c.validation==='approved').map(c=>`<tr><td>${c.kind==='structured'&&latest.has(c.id)&&c.validation!=='approved'?`<input type="checkbox" data-reference-question="${c.question_id}" aria-label="Select ${escape(c.question)}" ${S.selectedReferences.has(c.question_id)?'checked':''}>`:''}</td><td class="strong truncate">${escape(c.question||c.content.metadata?.file_title||'Document chunk')}<small>${escape(c.technology||c.source)}</small></td><td>v${c.version}</td><td>${badge(c.validation)}</td><td>${c.active?'Yes':'No'}</td><td>${button('Review','review-chunk',`data-id="${c.id}"`)}</td></tr>`)):empty('No reference chunks yet','Import a question catalog or upload a document to create reusable reference records.');}
function referenceSelection(){const count=$('#reference-selection-count');if(count)count.textContent=`${selectedChunks().length} selected`;}
async function bulkGenerate(rows){if(!rows.length)throw new Error('Select unapproved question references first.');await api('/references/bulk-generate',{application_id:S.app,chunk_ids:rows.map(c=>c.id)});toast('Generating proposals for all selected questions. Progress appears below.');await refreshJobs();}
function userDialog(id){const u=S.users.find(u=>u.id===id);modal(u?'Edit user':'Add user',`<form id="user-form" data-id="${u?.id||''}">${field('name','Name',u?.name||'')}${field('surname','Surname',u?.surname||'')}<div class="form-actions">${button('Cancel','close')}<button class="button primary" type="submit">Save user</button></div></form>`);}

function runCards(){return S.runs.length?S.runs.map(r=>`<article class="run-card"><div class="run-card-head"><div><h3>${escape(r.application)}</h3><p>${when(r.created_at)} <span class="mono">/ ${r.id.slice(0,8)}</span></p></div>${badge(r.status)}</div><div class="run-progress"><div class="progress-track"><span style="width:${r.total?r.finished/r.total*100:0}%"></span></div><span>${r.finished} / ${r.total} cases</span></div><div class="actions">${button('Results','open-run',`data-id="${r.id}"`)}${['cancelled','completed','completed_with_errors'].includes(r.status)?button('Remove run','delete-run',`data-id="${r.id}"`):''}${button('Confident AI','cloud-status',`data-id="${r.id}"`)}${['running'].includes(r.status)?button('Pause','run-control',`data-id="${r.id}" data-command="pause"`):''}${['pending','paused','interrupted'].includes(r.status)?button('Resume','run-control',`data-id="${r.id}" data-command="resume"`):''}${['running','pending','paused','interrupted'].includes(r.status)?button('Cancel','run-control',`data-id="${r.id}" data-command="cancel"`):''}${r.status==='completed_with_errors'?button('Retry judge errors only','run-control',`data-id="${r.id}" data-command="retry-evaluation"`):''}${r.status==='running'?button('Recover interrupted worker','recover-run',`data-id="${r.id}"`):''}</div></article>`).join(''):empty('No test runs yet','Select a dataset and metrics to start a controlled evaluation batch.',button('Create a test run','new-run','',true));}
function resultsTable(){const status=$('#result-status')?.value||'', technology=$('#result-technology')?.value||'';const rows=S.results.filter(r=>(!status||r.state===status)&&(!technology||r.snapshot.technology===technology));return rows.length?table(['Question','Technology','Candidate score','Quality score¹','Status',''],rows.map(r=>{const scores=Object.values(r.metrics).filter(m=>typeof m.score==='number').map(m=>m.quality_score??m.score);return `<tr><td class="strong truncate">${escape(r.snapshot.question)}</td><td>${escape(r.snapshot.technology)}</td><td>${escape(r.actual.score??'—')}</td><td>${scores.length?(scores.reduce((a,b)=>a+b,0)/scores.length).toFixed(2):'—'}</td><td>${badge(r.state)}</td><td>${button('Inspect','result-detail',`data-id="${r.id}"`)}</td></tr>`;}))+`<div class="panel-body subtle">¹ Mean of available selected quality checks (0–1). Inspect each result for individual metrics, unavailable checks, and reasons.</div>`:empty('No matching results','Run an evaluation or change the current filters.');}
function jobRegion(){return '<div id="job-region"></div>';}

async function connectionDialog(id){
  const app=S.bootstrap.applications.find(a=>a.id===id), c=app?.config||{};
  modal(app?'Application connection':'Add an application',`<form id="connection-form"><div class="notice">Start with the basics. For a website, save it first, sign in if needed, then choose <strong>Check connection</strong>. For exported results, no URL or login is needed.</div><div class="form-grid">${field('name','Application name',app?.name||'')}${select('kind','Connect using',[['browser','Website'],['api','API'],['import','Import results']],app?.kind==='interview'?'browser':app?.kind||'browser')}</div><div id="connection-url" class="section-gap">${field('url','Application address',c.url||'','url','Paste the website address or API endpoint.')}</div><div id="connection-token" class="section-gap hidden">${field('api_token','API access token (optional)','','password','Kept only for this server session. Leave blank if the API does not need a token.')}</div><details class="section-gap"><summary class="row-link">Advanced options · only if needed</summary><div class="form-grid section-gap">${field('timeout','Response timeout (seconds)',c.timeout||60,'number')}${field('storage_state_env','Existing browser session variable',c.storage_state_env||'')}</div><div class="field section-gap"><label for="advanced">Connection options</label><textarea id="advanced" name="advanced" class="code" rows="9">${json(c)}</textarea><small>Optional API paths, website selectors, pagination, or custom authentication. Check connection can suggest controls for accessible websites.</small></div><label class="check section-gap"><input type="checkbox" name="certificate_exception" ${c.certificate_exception_origin?'checked':''}><span>Allow the approved interview server certificate<small>Only for https://50.62.181.23:8501.</small></span></label></details><div class="form-actions">${button('Cancel','close')}<button class="button primary" type="submit">Save connection</button></div></form>`);
  connectionMode();
}
function connectionMode(){const mode=$('#kind')?.value;if(!mode)return;$('#connection-url')?.classList.toggle('hidden',mode==='import');$('#connection-token')?.classList.toggle('hidden',mode!=='api');}
function diagnosticsDialog(id,d){
  const app=S.bootstrap.applications.find(a=>a.id===id), controls=d.selectors?.visible_control_attributes||[], suggested=d.selectors?.suggested_controls||{};
  const options=[['','Not identified yet'],...controls.filter(c=>c.selector).map(c=>[c.selector,c.label||c.placeholder||`${c.tag.toLowerCase()} ${c.id||''}`])];
  if(app.kind==='import'){modal('Ready to import',`<div class="notice">This application is ready for exported records. Import a question catalog, then import test cases with their actual output.</div><div class="form-actions">${button('Done','close','',true)}</div>`);return;}
  if(app.kind==='api'){modal('API configuration checked',`<div class="notice">${app.config.adapter==='interview_api'?'The interview configuration API responded successfully. Use Interview automation to collect session questions.':'The API client is configured. An authorized catalog request or a small test submission will verify the endpoint response.'}</div><p>No test answers were submitted.</p><div class="form-actions">${button('Done','close','',true)}</div>`);return;}
  modal('Website connection checked',`<div class="notice">The website opened successfully. ${Object.keys(suggested).length} controls were identified automatically. Confirm the controls before your first test.</div><form id="inspect-form" data-id="${id}"><div class="form-grid">${select('input','Where answers are entered',options,app.config.input||suggested.input||'')}${select('submit','Button that sends an answer',options,app.config.submit||suggested.submit||'')}${field('response','Reply area',app.config.response||suggested.response||'')}${field('completion','Finished-response indicator',app.config.completion||'')}</div><p class="section-gap">If the reply area or completion indicator is blank, this website needs a one-time control mapping. No guesses are used for sending answers or detecting a finished response.</p><details class="section-gap"><summary class="row-link">Technical inspection details</summary><div class="detail-block section-gap"><pre>${json(d)}</pre></div></details><div class="form-actions">${button('Close','close')}<button class="button primary" type="submit">Save confirmed controls</button></div></form>`);
}
function importDialog(kind){if(!S.app){toast('Create an application first.',true);return;}const catalog=kind==='catalog';modal(catalog?'Import question catalog':'Import test dataset',`<form id="import-form" data-kind="${kind}">${catalog?'':field('name','Dataset name','Imported evaluation dataset')}<div class="notice">${catalog?'Records need technology and question. Optional fields include question_id, concepts, expected_answer, rubric, and difficulty.':'Records need question_id (local UUID from the catalog) and candidate_input. Add actual {output, score} for offline evaluation. Optional score_range and expected_concepts require review.'}</div><div class="file-drop"><strong>Choose a JSON or CSV file</strong><input type="file" name="file" accept=".json,.csv" aria-label="Import file"></div><div class="field section-gap"><label for="records">Or paste a JSON array</label><textarea name="records" id="records" class="code" rows="8" placeholder="[]"></textarea></div><div class="form-actions">${button('Cancel','close')}<button class="button primary" type="submit">Import for review</button></div></form>`);}
async function generationDialog(){if(!S.app){toast('Create an application first.',true);return;}S.catalog=await api('/catalog/'+S.app);const references=await api('/chunks?kind=structured&app_id='+S.app), latest={};for(const ref of references){if(ref.active&&(!latest[ref.question_id]||ref.version>latest[ref.question_id].version))latest[ref.question_id]=ref;}const ready=q=>latest[q.id]?.validation==='approved';modal('Generate candidate test cases',`<form id="generate-form">${field('name','Dataset name','Interview regression')}<div class="section-heading"><h3>Questions</h3><label class="check"><input type="checkbox" data-action="select-all" data-group="question_ids" checked>Select approved questions</label></div><div class="notice">Only questions with an approved latest reference can generate test cases. Click Review reference, check the approval box, and Save new version. Then reopen this dialog.</div><div class="selection-list">${S.catalog.questions.map(q=>`<div><label><input type="checkbox" name="question_ids" value="${q.id}" ${ready(q)?'checked':'disabled'}><span>${escape(q.text)}<small>${escape(q.technology)} · ${ready(q)?'Approved — ready':'Reference needs approval'}</small></span></label>${!ready(q)&&latest[q.id]?button('Review reference','review-generation-reference',`data-id="${latest[q.id].id}"`):''}</div>`).join('')||'<div class="empty">Import questions first.</div>'}</div><div class="section-heading"><h3>Answer categories</h3></div><div class="metric-grid">${S.bootstrap.categories.map((c,i)=>`<label class="metric-option"><input type="checkbox" name="categories" value="${escape(c)}" ${[0,1,5].includes(i)?'checked':''}><span>${escape(c)}</span></label>`).join('')}</div><div class="section-gap">${field('count','Cases per category per question',1,'number')}</div><div class="notice">Selected questions must have approved references. Generation uses your configured model; generated answers and expectations are saved as unverified.</div><div class="form-actions">${button('Cancel','close')}<button class="button primary" type="submit" ${S.catalog.questions.some(ready)?'':'disabled'}>Generate dataset</button></div></form>`);}
async function runDialog(){
  if(!S.app){toast('Create an application first.',true);location.hash='applications';return;}
  S.datasets=await api('/datasets/'+S.app);if(!S.datasets.length){toast('Create or import a dataset first.',true);location.hash='datasets';return;}
  const dataset=S.datasets.find(d=>d.id===S.dataset)||S.datasets[0];S.dataset=dataset.id;S.cases=await api('/dataset/'+S.dataset+'/cases');
  modal('Create a test run',`<form id="run-form"><div class="form-grid">${select('run_application','Application',S.bootstrap.applications.map(a=>[a.id,a.name]),S.app)}${select('run_dataset','Dataset',S.datasets.map(d=>[d.id,`${d.name} (${d.cases} cases)`]),S.dataset)}</div><div class="section-heading"><h3>Test cases</h3><label class="check"><input type="checkbox" data-action="select-all" data-group="case_ids" checked>Select all</label></div><div id="run-cases" class="selection-list">${runCaseChoices()}</div><div class="section-heading"><h3>DeepEval metrics</h3><span class="subtle">All DeepEval checks selected; missing required data is reported.</span></div><div class="metric-grid">${S.bootstrap.metrics.filter(m=>!m.legacy).map(m=>`<label class="metric-option"><input type="checkbox" name="metrics" value="${escape(m.name)}" ${m.default?'checked':''}><span>${escape(m.name)}<small>${escape(m.requires||'Input and actual output')}</small><small>${escape(m.implementation)}</small></span></label>`).join('')}</div><div class="form-grid section-gap">${field('threshold','Quality threshold (0–1)',.5,'number')}${field('batch_size','Cases per batch',25,'number')}${field('interval','Seconds between cases',1,'number')}<div class="field"><label for="custom_criteria">Custom criteria (optional)</label><textarea name="custom_criteria" id="custom_criteria"></textarea></div></div><div class="notice">Reference-dependent checks are unavailable without approved ground truth. Live connections can create test records in the target application; use your dedicated test account.</div><div class="form-actions">${button('Cancel','close')}<button class="button primary" type="submit">Start test run</button></div></form>`);
  $('#threshold').step='0.05';$('#threshold').min='0';$('#threshold').max='1';
}
function runCaseChoices(){return S.cases.map(c=>`<label><input type="checkbox" name="case_ids" value="${c.id}" checked><span>${escape(c.question)}<small>${escape(c.technology)} · ${escape(c.content.category||'Imported')} · ${escape(c.validation)}</small></span></label>`).join('');}
function reviewChunk(id){
  const c=S.chunks.find(c=>c.id===id);
  const simple=c.kind==='structured'?`<div class="field section-gap"><label for="reference-answer">Expected answer</label><textarea id="reference-answer" name="expected_answer" rows="5">${escape(c.content.expected_answer||'')}</textarea></div><div class="field section-gap"><label for="reference-concepts">Core concepts · one per line</label><textarea id="reference-concepts" name="concepts" rows="5">${escape((c.content.concepts||[]).map(x=>typeof x==='string'?x:x.description||JSON.stringify(x)).join('\n'))}</textarea><small>Existing concept weights and alternatives are retained when a concept is unchanged.</small></div>`:'';
  modal('Review reference version',`<form id="chunk-form" data-id="${id}"><div class="actions">${badge(c.validation)}<span class="subtle">Version ${c.version} · ${escape(c.source)}</span></div><h3 class="section-gap">${escape(c.question||'Document chunk')}</h3>${simple}<details class="section-gap" ${c.kind==='document'?'open':''}><summary class="row-link">Advanced reference data and rubric</summary><div class="field section-gap"><label for="chunk-content">Complete reference record</label><textarea name="content" id="chunk-content" class="code" rows="12">${json(c.content)}</textarea></div></details><label class="check section-gap"><input type="checkbox" name="approved"><span>I reviewed this content and approve it for evaluation</span></label><div class="form-actions">${c.kind==='structured'?button('Generate proposal','generate-reference',`data-id="${id}"`):''}${button('Deactivate','deactivate-chunk',`data-id="${id}"`)}<button class="button primary" type="submit">Save new version</button></div></form>`);
}
function reviewCase(id){
  const c=S.cases.find(c=>c.id===id);
  modal('Review test case',`<form id="case-form" data-id="${id}"><h3>${escape(c.question)}</h3><p>${escape(c.technology)} · ${escape(c.content.category||'Imported')}</p><div class="field section-gap"><label for="candidate-answer">Candidate answer</label><textarea id="candidate-answer" name="candidate_input" rows="5">${escape(c.content.candidate_input)}</textarea></div><div class="field section-gap"><label for="expected-evaluation">Expected evaluation</label><textarea id="expected-evaluation" name="expected_output" rows="4">${escape(c.content.expected_output||'')}</textarea></div><div class="form-grid section-gap">${field('score_min','Expected score minimum',c.content.score_range?.[0]??'','number')}${field('score_max','Expected score maximum',c.content.score_range?.[1]??'','number')}</div><p>Only set a score range when you have a reviewed scoring basis. Leave both fields blank otherwise.</p><details class="section-gap"><summary class="row-link">Advanced case data and captured output</summary><div class="field section-gap"><textarea name="content" class="code" rows="12" aria-label="Complete test case">${json(c.content)}</textarea></div></details><label class="check section-gap"><input type="checkbox" name="approved" ${c.validation==='approved'?'checked':''}><span>I reviewed and approve this answer and expected outcome</span></label><div class="form-actions">${button('Cancel','close')}${button('Generate proposal','generate-case-proposal',`data-id="${id}"`)}<button class="button primary" type="submit">Save review</button></div></form>`);
}
function resultDetail(id){const r=S.results.find(r=>r.id===id),c=JSON.parse(r.snapshot.content);modal('Evaluation detail',`<div class="actions">${badge(r.state)}<span class="subtle">${escape(r.snapshot.technology)} · ${when(r.updated_at)}</span></div><h3 class="section-gap">${escape(r.snapshot.question)}</h3>${r.error?`<div class="notice red">${escape(r.error)}</div>`:''}<div class="details-grid section-gap"><div class="detail-block"><h3>Candidate answer</h3><pre>${escape(c.candidate_input||'(Empty answer)')}</pre></div><div class="detail-block"><h3>Expected evaluation</h3><pre>${json({expected_output:c.expected_output,score_range:c.score_range,expected_concepts:c.expected_concepts,validation:r.snapshot.validation})}</pre></div><div class="detail-block"><h3>Actual application evaluation</h3><pre>${json(r.actual)}</pre></div><div class="detail-block"><h3>Reference snapshot</h3><pre>${r.snapshot.reference?json({...JSON.parse(r.snapshot.reference.content),validation:r.snapshot.reference.validation,version:r.snapshot.reference.version}):'No reference available'}</pre></div></div><div class="section-heading"><h3>Evaluation quality · 0 to 1</h3></div>${Object.entries(r.metrics).map(([name,m])=>`<div class="metric-result"><header><strong>${escape(name)}</strong><span>${m.score===undefined?'—':Number(m.score).toFixed(2)} ${badge(m.status)}</span></header><p>${escape(m.reason)}</p><small>${escape(m.engine||'Legacy result')} · ${escape(m.implementation||'Implementation not recorded')}</small></div>`).join('')||'<p>No metrics captured yet.</p>'}`);}

document.addEventListener('click',async event=>{
  const target=event.target.closest('[data-action]');if(!target)return;const action=target.dataset.action,id=target.dataset.id;
  if(target.type==='checkbox'&&action==='select-all'){$$(`input[name="${target.dataset.group}"]:not(:disabled)`,$('#modal')).forEach(c=>c.checked=target.checked);return;}
  event.preventDefault();
  try{
    if(action==='add-user'||action==='edit-user')return userDialog(id);
    if(action==='select-all-references'||action==='clear-references'){S.selectedReferences=new Set(action==='clear-references'?[]:currentChunks().filter(c=>!$('#reference-approved-only')?.checked&&c.validation!=='approved').map(c=>c.question_id));$('#chunks-table').innerHTML=chunkTable();referenceSelection();return;}
    if(action==='bulk-generate-references')return await bulkGenerate(selectedChunks());
    if(action==='bulk-approve-references'){const rows=selectedChunks();if(!rows.length)throw new Error('Select unapproved references first.');const missing=rows.filter(c=>!c.content.expected_answer&&!c.content.concepts?.length&&!c.content.rubric);if(missing.length){await bulkGenerate(missing);toast('Missing references are being generated. Review the proposals when finished, then approve selected.');return;}modal('Review and approve selected references',`<form id="bulk-approve-form" data-ids="${escape(JSON.stringify(rows.map(c=>c.id)))}"><p>Approve ${rows.length} selected references. Each approval saves a new version.</p>${rows.map(c=>`<div class="detail-block section-gap"><h3>${escape(c.question)}</h3><pre>${json(c.content)}</pre></div>`).join('')}<label class="check section-gap"><input type="checkbox" name="reviewed" required><span>I reviewed this content and approve it for evaluation</span></label><div class="form-actions">${button('Cancel','close')}<button class="button primary" type="submit">Approve & save selected</button></div></form>`);return;}
    if(action==='logout'){await api('/logout',{});showSignIn();return;}
    if(action==='delete-user'||action==='delete-application'){modal('Remove from workspace',`<p>${action==='delete-user'?'Remove this user and revoke their sessions? Audit history is retained.':'Remove this application connection? Historical results are retained; the remote application is not changed.'}</p><div class="form-actions">${button('Keep it','close')}${button('Confirm removal','confirm-delete',`data-kind="${action==='delete-user'?'users':'connections'}" data-id="${id}"`,true)}</div>`);return;}
    if(action==='restore-user'){await api('/users/'+id+'/restore',{});await render();return;}
    if(action==='delete-dataset'||action==='delete-run'){modal('Remove from workspace',`<p>${action==='delete-dataset'?'Remove this dataset from the dataset list? Existing run history will be retained.':'Remove this completed or cancelled run from the run list? Historical and audit records will be retained.'}</p><div class="form-actions">${button('Keep it','close')}${button('Confirm removal','confirm-delete',`data-kind="${action==='delete-dataset'?'datasets':'runs'}" data-id="${id}"`,true)}</div>`);return;}
    if(action==='confirm-delete'){await api(`/${target.dataset.kind}/${id}`,undefined,'DELETE');closeModal();if(target.dataset.kind==='datasets')S.dataset='';await render();toast('Removed from workspace.');return;}
    if(action==='activity'){const rows=await api('/activity');modal('User activity',table(['User','Action','Record','Status','When'],rows.map(r=>`<tr><td>${escape(r.actor)}</td><td>${escape(r.action)}</td><td>${escape(r.target)}</td><td>${r.status}</td><td>${escape(r.created_at)}</td></tr>`)));return;}
    if(action==='refresh')return await render();if(action==='close')return closeModal();if(action==='settings'){location.hash='settings';return;}
    if(action==='interview-setup')return await interviewSetup(id);
    if(action==='interview-first-test'){target.disabled=true;const result=await api(`/connections/${id}/interview-first-test`,{});toast(result.message);S.run=result.run_id;location.hash='runs';return;}
    if(action==='cloud-status'){const c=await api(`/runs/${id}/cloud-status`);const link=c.confident_link?.startsWith('https://app.confident-ai.com/')?`<a class="button primary" href="${escape(c.confident_link)}" target="_blank" rel="noopener">Open cloud report</a>`:'';modal('Confident AI sync',`<p>${badge(c.state)}</p><p>${escape(c.message)}</p><p>Cases, captured feedback, metric scores, reasons and unavailable checks are uploaded. Retrying sync does not submit answers or run the judge again.</p><div class="form-actions">${link}${button('Sync to Confident AI','run-control',`data-id="${id}" data-command="cloud-sync"`)}${button('Close','close')}</div>`);return;}
    if(action==='new-connection'||action==='edit-connection')return await connectionDialog(id);
    if(action==='login'){await api(`/connections/${id}/login`,{});modal('Sign in to your application',`<p>A browser window will open. Sign in with your dedicated test account, then return here.</p><div class="notice">Your login session stays on this computer and is excluded from GitHub.</div><div class="form-actions">${button('Finish sign-in','finish-login',`data-id="${id}"`,true)}</div>`);return;}
    if(action==='finish-login'){await api(`/connections/${id}/login/complete`,{});closeModal();toast('Saving your local sign-in session.');await refreshJobs();return;}
    if(action==='import-catalog')return importDialog('catalog');if(action==='import-dataset')return importDialog('dataset');
    if(action==='generate-dataset')return await generationDialog();if(action==='new-run')return await runDialog();
    if(action==='clear-cases'){S.selectedCases.clear();$$('[data-case-id]').forEach(n=>n.checked=false);return;}
    if(action==='select-all-cases'){for(const c of S.cases)if(c.validation!=='approved')S.selectedCases.add(c.id);$$('[data-case-id]').forEach(n=>n.checked=true);return;}
    if(action==='generate-case-proposals')return await generateCaseProposals(selectedCases());
    if(action==='generate-case-proposal'){const c=S.cases.find(c=>c.id===id),f=$('#case-form');if([...f.elements].some(n=>n.type==='checkbox'?n.checked!==n.defaultChecked:('defaultValue' in n&&n.value!==n.defaultValue)))throw new Error('Save your review edits first, then reopen Review to generate a proposal.');return await generateCaseProposals([c]);}
    if(action==='approve-cases'){const rows=selectedCases();if(!rows.length)throw new Error('Select unapproved cases first.');const missing=rows.filter(c=>!c.content.expected_output&&!c.content.score_range&&!c.content.expected_concepts);if(missing.length){await generateCaseProposals(missing);return;}modal('Review and approve selected cases',`<form id="approve-cases-form"><p>Review the selected answers and proposed expectations below.</p>${rows.map(c=>`<div class="detail-block section-gap"><h3>${escape(c.question)}</h3><pre>${json(c.content)}</pre></div>`).join('')}<label class="check section-gap"><input name="reviewed" type="checkbox" required>I reviewed this content and approve it for evaluation</label><div class="form-actions">${button('Cancel','close')}<button type="submit" class="button primary">Approve & save selected</button></div></form>`);S.caseApproval=rows.map(c=>({id:c.id,content:c.content}));return;}
    if(action==='review-generation-reference'){S.chunks=await api('/chunks?kind=structured&app_id='+S.app);return reviewChunk(id);}
    if(action==='review-chunk')return reviewChunk(id);if(action==='review-case')return reviewCase(id);if(action==='result-detail')return resultDetail(id);
    if(action==='select-dataset'){S.selectedCases.clear();S.dataset=id;return await render();}
    if(action==='open-run'){S.run=id;location.hash='results';if(S.view==='results')await render();return;}
    if(action==='export-dataset')return download('dataset.json',S.cases.map(c=>c.content));if(action==='export-references')return download('references.json',S.chunks);
    if(action==='question-reference'){S.chunks=await api('/chunks?app_id='+S.app);const c=S.chunks.find(c=>c.question_id===id&&c.active);if(!c)throw new Error('No active reference chunk found.');return reviewChunk(c.id);}
    if(action==='diagnostics'){target.disabled=true;const d=await api(`/connections/${id}/diagnostics`,{});diagnosticsDialog(id,d);return;}
    if(action==='sync-technologies'||action==='sync-questions'){if(currentApp()?.kind==='import')throw new Error('Use Import catalog for an offline connection.');await api(`/connections/${S.app}/synchronize`,{technologies_only:action==='sync-technologies'});toast('Synchronization started. Follow progress below.');return await refreshJobs();}
    if(action==='deactivate-chunk'){await api(`/chunks/${id}/deactivate`,{});closeModal();toast('Reference version deactivated.');return await render();}
    if(action==='generate-reference'){await api(`/chunks/${id}/generate`,{});closeModal();toast('Generating an unverified independent reference.');return await refreshJobs();}
    if(action==='run-control'){await api(`/runs/${id}/${target.dataset.command}`,{});toast('Run control updated.');return await render();}
    if(action==='recover-run'){modal('Recover an interrupted worker',`<p>Recovery is allowed only after the prior worker has exited. The server also checks its process lock.</p><div class="notice amber">Cases interrupted during submission remain held for review. Recovery will not submit them again.</div><div class="form-actions">${button('Cancel','close')}${button('Recover run','confirm-recover',`data-id="${id}"`,true)}</div>`);return;}
    if(action==='confirm-recover'){await api(`/runs/${id}/recover`,{});closeModal();toast('Recovered. Review held submissions before resuming.');return await render();}
    if(action==='rag-synthesize'){modal('Generate RAG goldens',`<form id="rag-synthesize-form" data-id="${id}"><div class="form-grid">${field('max_chunks','Maximum chunks',10,'number')}${field('target','Target Q&A pairs',5,'number')}</div><div class="notice">Uses DeepEval synthesis and your configured model. Generated expected answers should be reviewed.</div><div class="form-actions">${button('Cancel','close')}<button class="button primary" type="submit">Generate goldens</button></div></form>`);return;}
    if(action==='rag-review'){const row=S.rag.snapshots.find(s=>s.id===id);modal('Review RAG golden dataset',`<form id="rag-review-form" data-id="${id}"><div class="field"><label for="goldens">Questions, expected answers, context, and captured results</label><textarea id="goldens" name="goldens" class="code" rows="20">${json(row.goldens)}</textarea></div><div class="form-actions">${button('Export JSON','rag-export',`data-id="${id}"`)}<a class="button" href="/api/rag/snapshots/${id}/export?format=pdf">PDF</a><a class="button" href="/api/rag/snapshots/${id}/export?format=docx">Word</a><button class="button primary" type="submit">Save reviewed version</button></div></form>`);return;}
    if(action==='rag-export'){return download('rag-goldens.json',S.rag.snapshots.find(s=>s.id===id).goldens);}
    if(action==='rag-evaluate'){modal('Evaluate RAG dataset',`<form id="rag-evaluate-form" data-id="${id}"><div class="metric-grid">${S.bootstrap.metrics.filter(m=>m.name.startsWith('RAG ')).map(m=>`<label class="metric-option"><input type="checkbox" name="metrics" value="${escape(m.name)}" checked><span>${escape(m.name)}<small>${escape(m.requires||'Input and actual output')}</small></span></label>`).join('')}</div><div class="notice">This calls your configured RAG endpoint. Context-dependent metrics require retrieval_context in the actual response. Missing context is reported as unavailable.</div><div class="form-actions">${button('Cancel','close')}<button class="button primary" type="submit">Run evaluation</button></div></form>`);return;}
  }catch(e){toast(e.message,true);}finally{target.disabled=false;}
});

document.addEventListener('change',async event=>{
  const node=event.target;try{
    if(node.dataset.caseId){if(node.checked)S.selectedCases.add(node.dataset.caseId);else S.selectedCases.delete(node.dataset.caseId);}
    if(node.dataset.referenceQuestion){if(node.checked)S.selectedReferences.add(node.dataset.referenceQuestion);else S.selectedReferences.delete(node.dataset.referenceQuestion);referenceSelection();}
    if(node.id==='reference-history'||node.id==='reference-approved-only'){S.selectedReferences.clear();$('#chunks-table').innerHTML=chunkTable();referenceSelection();}
    if(node.id==='kind')connectionMode();
    if(node.id==='interview-domain'){const d=await api(`/connections/${$('#interview-form').dataset.id}/interview-options?domain_id=${encodeURIComponent(node.value)}`);$('#interview-technologies').innerHTML=interviewTechnologies(d.technologies,[]);}
    if(node.id==='app-picker'){S.selectedReferences.clear();S.app=node.value;S.dataset='';await render();}
    if(node.id==='technology-filter')$('#question-table').innerHTML=questionTable();
    if(node.id==='chunk-kind'){S.selectedReferences.clear();$('#reference-bulk-toolbar').classList.toggle('hidden',node.value!=='structured');S.chunks=await api('/chunks?kind='+node.value+(node.value==='structured'?'&app_id='+S.app:''));$('#chunks-table').innerHTML=chunkTable();}
    if(node.id==='result-run'){S.run=node.value;await render();}
    if(['result-status','result-technology'].includes(node.id))$('#results-table').innerHTML=resultsTable();
    if(node.id==='run_application'){S.app=node.value;closeModal();await runDialog();}
    if(node.id==='run_dataset'){S.dataset=node.value;S.cases=await api('/dataset/'+S.dataset+'/cases');$('#run-cases').innerHTML=runCaseChoices();}
  }catch(e){toast(e.message,true);}
});

document.addEventListener('submit',async event=>{
  event.preventDefault();const form=event.target,values=formData(form),submit=$('[type="submit"]',form);if(submit)submit.disabled=true;
  try{
    if(form.id==='approve-cases-form'){await api('/case-actions/approve',{dataset_id:S.dataset,items:S.caseApproval,reviewed:!!values.reviewed});S.selectedCases.clear();closeModal();await render();toast('Selected cases approved.');return;}
    if(form.id==='user-form'){await api(form.dataset.id?'/users/'+form.dataset.id:'/users',values,form.dataset.id?'PUT':'POST');closeModal();await render();toast('User saved.');return;}
    if(form.id==='bulk-approve-form'){await api('/references/bulk-approve',{application_id:S.app,chunk_ids:JSON.parse(form.dataset.ids),reviewed:!!values.reviewed});S.selectedReferences.clear();closeModal();await render();toast('Selected references approved and saved.');return;}
    if(form.id==='login-form'){await api('/login',values);form.reset();await render();return;}
    if(form.id==='interview-form'){const technologies=$$('input[name="interview_technology"]:checked',form).map(e=>Number(e.value));const result=await api(`/connections/${form.dataset.id}/interview-setup`,{domain_id:Number(values['interview-domain']),level_rank:Number(values['interview-level']),practice_type:values['interview-practice'],technology_ids:technologies});closeModal();toast(`Automation configured. ${result.questions} session questions collected.`);S.bootstrap=await api('/bootstrap');await render();return;}
    if(form.id==='connection-form'){
      const config=JSON.parse(values.advanced||'{}');for(const key of ['url','input','submit','response','completion','question','reset','technology_select','question_select','catalog_path','submit_path','token_env','storage_state_env']){if(values[key]!==undefined){if(values[key])config[key]=values[key];else delete config[key];}}
      config.timeout=Number(values.timeout);config.headless=true;config.browser_channel=config.browser_channel??'msedge';
      if(values.certificate_exception)config.certificate_exception_origin='https://50.62.181.23:8501';else delete config.certificate_exception_origin;
      const kind=values.kind==='browser'&&config.url?.startsWith('https://50.62.181.23:8501')?'interview':values.kind;
      const r=await api('/connections',{name:values.name,kind,config,api_token:values.api_token||''});S.app=r.id;closeModal();toast('Application saved.');await render();
    }else if(form.id==='inspect-form'){const app=S.bootstrap.applications.find(a=>a.id===form.dataset.id);await api('/connections',{name:app.name,kind:app.kind,config:{...app.config,...values}});closeModal();toast('Connection controls saved.');await render();}
    else if(form.id==='settings-form'){const r=await api('/settings',values);toast(r.message);form.openai_key.value='';form.supabase_key.value='';form.confident_key.value='';}
    else if(form.id==='import-form'){
      let records;const file=form.file.files[0];if(file){const data=new FormData();data.append('file',file);records=await api('/imports/parse',data);}else records=JSON.parse(values.records);
      if(form.dataset.kind==='catalog')await api('/catalog/'+S.app+'/import',{records});else await api('/datasets/'+S.app+'/import',{name:values.name,cases:records});
      closeModal();toast('Import saved for review.');await render();
    }else if(form.id==='generate-form'){
      await api('/datasets/'+S.app+'/generate',{name:values.name,question_ids:checked(form,'question_ids'),categories:checked(form,'categories'),count:Number(values.count)});closeModal();toast('Dataset generation started.');await refreshJobs();
    }else if(form.id==='chunk-form'){
      const content=JSON.parse(values.content),original=S.chunks.find(c=>c.id===form.dataset.id).content;
      if(values.expected_answer!==undefined)content.expected_answer=values.expected_answer;
      if(values.concepts!==undefined)content.concepts=values.concepts.split('\n').map(x=>x.trim()).filter(Boolean).map(line=>(original.concepts||[]).find(x=>(typeof x==='string'?x:x.description||JSON.stringify(x))===line)||line);
      await api('/chunks/'+form.dataset.id+'/version',{content,validation:values.approved?'approved':'unverified'});closeModal();toast('New reference version saved.');await render();
    }else if(form.id==='case-form'){
      const content={...JSON.parse(values.content),candidate_input:values.candidate_input,expected_output:values.expected_output};
      if(values.score_min!==''||values.score_max!==''){if(values.score_min===''||values.score_max==='')throw new Error('Provide both score bounds or leave both blank.');content.score_range=[Number(values.score_min),Number(values.score_max)];if(content.score_range[0]>content.score_range[1])throw new Error('Minimum score must not exceed maximum.');}else delete content.score_range;
      await api('/cases/'+form.dataset.id,{content,approved:!!values.approved});closeModal();toast('Test case saved.');await render();
    }
    else if(form.id==='run-form'){
      const r=await api('/runs',{application_id:S.app,case_ids:checked(form,'case_ids'),config:{metrics:checked(form,'metrics'),threshold:Number(values.threshold),batch_size:Number(values.batch_size),interval:Number(values.interval),custom_criteria:values.custom_criteria},start:true});S.run=r.id;closeModal();location.hash='runs';toast('Test run started.');if(S.view==='runs')await render();
    }else if(form.id==='upload-form'){const r=await api('/rag/upload',new FormData(form));toast(r.warning||`${r.chunks} document chunks saved.`,!!r.warning);await render();}
    else if(form.id==='rag-synthesize-form'){await api('/rag/synthesize',{document_id:form.dataset.id,max_chunks:Number(values.max_chunks),target:Number(values.target)});closeModal();toast('RAG synthesis started.');await refreshJobs();}
    else if(form.id==='rag-review-form'){await api('/rag/snapshots/'+form.dataset.id,{goldens:JSON.parse(values.goldens)});closeModal();toast('Reviewed version saved.');await render();}
    else if(form.id==='rag-evaluate-form'){await api('/rag/evaluate',{snapshot_id:form.dataset.id,metrics:checked(form,'metrics')});closeModal();toast('RAG evaluation started.');await refreshJobs();}
  }catch(e){toast(e.message,true);}finally{if(submit)submit.disabled=false;}
});
async function refreshJobs(){const region=$('#job-region');if(!region)return;try{const jobs=await api('/jobs');if(S.view==='datasets'&&jobs.some(j=>j.kind==='Test-case proposals'&&j.state==='completed'&&!S.caseJobs.has(j.id))){for(const j of jobs.filter(j=>j.kind==='Test-case proposals'&&j.state==='completed'))S.caseJobs.add(j.id);await render();return;}if(S.view==='references'&&jobs.some(j=>['Bulk reference proposals','Independent reference proposal'].includes(j.kind)&&j.state==='completed'&&!S.referenceJobs.has(j.id))){for(const j of jobs.filter(j=>j.state==='completed'))S.referenceJobs.add(j.id);S.chunks=await api('/chunks?kind=structured'+(S.app?'&app_id='+S.app:''));if($('#chunks-table')){$('#chunks-table').innerHTML=chunkTable();referenceSelection();}}region.innerHTML=jobs.slice(0,4).map(j=>`<div class="job-box"><header><strong>${escape(j.kind)}</strong>${badge(j.state)}</header><div class="progress-track"><span style="width:${j.progress*100}%"></span></div><p>${escape(j.message||'Queued')}</p></div>`).join('');}catch{/* Normal page errors are handled by the main renderer. */}}
window.addEventListener('hashchange',render);
setInterval(async()=>{if(!S.user||document.hidden||$('#modal').open)return;await refreshJobs();if(S.view==='runs'&&$('#run-list')){try{S.runs=await api('/runs');$('#run-list').innerHTML=runCards();}catch{}}},3000);
render().catch(e=>{showSignIn();toast(e.message,true);});

function interviewTechnologies(options, selected){return options.map(t=>`<label class="check"><input type="checkbox" name="interview_technology" value="${t.TechnologyID}" ${selected.includes(t.TechnologyID)?'checked':''}>${escape(t.TechnologyName)}</label>`).join('');}
async function interviewSetup(id){
 const c=S.bootstrap.applications.find(a=>a.id===id).config;
 const domain=c.domain_id||3, d=await api(`/connections/${id}/interview-options?domain_id=${domain}`);
 modal('Automate AI Interview',`<form id="interview-form" data-id="${id}"><div class="notice">Uses the same practice API as the interview website. No browser mapping or server-code changes are needed. Saving collects session questions; it does not submit answers.</div><div class="form-grid section-gap">${select('interview-practice','Practice type',[['Technical','Technical'],['Non-Technical','Non-Technical'],['Mixed','Mixed']],c.practice_type||'Technical')}${select('interview-domain','Domain',d.domains.map(v=>[v.DomainID,v.DomainName]),domain)}${select('interview-level','Proficiency',d.proficiencies.map(v=>[v.LevelRank,v.ProficiencyLevelName]),c.level_rank||2)}</div><h3 class="section-gap">Technologies</h3><div id="interview-technologies" class="metric-grid">${interviewTechnologies(d.technologies,c.technology_ids||[4])}</div><p>For the starter test choose Data Analytics, SQL and Basic Meaning. Other tests use your reviewed datasets and selected metrics.</p><div class="form-actions">${button('Cancel','close')}<button class="button primary" type="submit">Save & collect questions</button></div></form>`);
}

function selectedCases(){return S.cases.filter(c=>S.selectedCases.has(c.id)&&c.validation!=='approved');}
async function generateCaseProposals(rows){if(!rows.length)throw new Error('Select test cases first.');await api('/case-actions/generate',{dataset_id:S.dataset,items:rows.map(c=>({id:c.id,content:c.content}))});closeModal();toast('Generating proposals from saved answers. Cases refresh when finished; review and approve selected.');await refreshJobs();}
